name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-utiles:
    runs-on: ubuntu-latesr
    steps:
      - name: Checkout and Clone
        uses: actions/checkout@v2.4.2
      - name: Install Dependencies
        run: npm install
      -name: Test Utils
        run: test-utils

  test-app:
    runs-on: ubuntu-latest
    needs: test-utils
    steps:
      - name: Checkout and Clone
        uses: actions/checkout@v2.4.2
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql: nc_games_test
          postgresql user: bumble_test
          postgresql password: password
      - name: Install dependencies
        run: npm install
      - name: Test app
        run: PGDATABASE=nc_games_test PGUSER=bumble_test PGPASSWORD=password npm run test-app

  deploy:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Checkout and Clone
        uses: actions/checkout@v2.4.2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
